#!/bin/bash
#
# Hack the AD_DOMAIN, CLOUD_USER, HTTPS_PROXY variables if needed
#
test -n "$SET_MINUSX" && set -x

test -z "$XFER_SP_FILE_USER" && USAGE=t
test -z "$XFER_SP_FILE_PASSWORD" && USAGE=t
test "$#" != 2 && USAGE=t


if test -n "$USAGE"
then
    echo Usage   : $0 https://yoyodyne.sharepoint.com/sites/etl SP_LIST
    echo Env Var XFER_SP_FILE_USER should contain ldap user id
    echo Env Var XFER_SP_FILE_PASSWORD should contain password
    exit 1
fi

CLOUD_SP=$1
SP_LIST=$2
AD_DOMAIN=YOYODYNE
AD_USER="$AD_DOMAIN\\$XFER_SP_FILE_USER"

if echo $CLOUD_SP|grep sharepoint.com > /dev/null
then
    CLOUD_USER="$XFER_SP_FILE_USER@yoyodyne.com"
    export HTTPS_PROXY=https://proxy.yoyodyne.com:8080
else
    true
fi

if test -n "$XFER_SP_FILE_VERBOSE"
then
    CURL_NOISE=-v
else
    CURL_NOISE=-s
fi

if test -f $(dirname $0)/USE_THIS_AS_TMP_DIR
then
	TMP_DIR=$(cd $(dirname $0) && pwd)
else
	TMP_DIR=/tmp/tmp-$$-$(basename $0)
	mkdir -p $TMP_DIR || exit 1
	trap "rm -rf $TMP_DIR" EXIT
fi

cd $TMP_DIR || exit 1

AUTH=--ntlm
NETRC_FILE=$TMP_DIR/.netrc
CURL=/usr/bin/curl

touch $NETRC_FILE 
chmod go-rwx $NETRC_FILE

SITE=$(echo $CLOUD_SP | perl -p -e 's!^https*://!!;s!(:\d+)*/.*!!')

cat > $NETRC_FILE <<EOF
machine $SITE login $AD_USER password $XFER_SP_FILE_PASSWORD
EOF

export HOME=$TMP_DIR

AUTH=--proxy-anyauth
COOKIE_FILE=$TMP_DIR/Cookies.txt
CURL_DGST_RESP=$TMP_DIR/CurlDigestResponse.txt
CURL_SAML_RESP=$TMP_DIR/CurlSAMLResponse.txt
CURL_RESP=$TMP_DIR/CurlResponse.txt
CURL_HDR=$TMP_DIR/CurlHeader.txt
SAML_FILE=$TMP_DIR/SAML.dat
FORM_FILE=$TMP_DIR/FORM.dat
DOT_FILE=$TMP_DIR/dot_file.txt

for p in $COOKIE_FILE $CURL_DGST_RESP $CURL_SAML_RESP $CURL_HDR $CURL_RESP $SAML_FILE $FORM_FILE $DOT_FILE
do
    touch $p
    chmod go-rwx $p
done

cat > $SAML_FILE <<EOF
<s:Envelope xmlns:s='http://www.w3.org/2003/05/soap-envelope'
      xmlns:a='http://www.w3.org/2005/08/addressing'
      xmlns:u='http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd'>
  <s:Header>
    <a:Action s:mustUnderstand='1'>http://schemas.xmlsoap.org/ws/2005/02/trust/RST/Issue</a:Action>
    <a:ReplyTo>
      <a:Address>http://www.w3.org/2005/08/addressing/anonymous</a:Address>
    </a:ReplyTo>
    <a:To s:mustUnderstand='1'>https://login.microsoftonline.com/extSTS.srf</a:To>
    <o:Security s:mustUnderstand='1'
       xmlns:o='http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd'>
      <o:UsernameToken>
        <o:Username>$CLOUD_USER</o:Username>
        <o:Password>$XFER_SP_FILE_PASSWORD</o:Password>
      </o:UsernameToken>
    </o:Security>
  </s:Header>
  <s:Body>
    <t:RequestSecurityToken xmlns:t='http://schemas.xmlsoap.org/ws/2005/02/trust'>
      <wsp:AppliesTo xmlns:wsp='http://schemas.xmlsoap.org/ws/2004/09/policy'>
        <a:EndpointReference>
          <a:Address>$SITE</a:Address>
        </a:EndpointReference>
      </wsp:AppliesTo>
      <t:KeyType>http://schemas.xmlsoap.org/ws/2005/05/identity/NoProofKey</t:KeyType>
      <t:RequestType>http://schemas.xmlsoap.org/ws/2005/02/trust/Issue</t:RequestType>
      <t:TokenType>urn:oasis:names:tc:SAML:1.0:assertion</t:TokenType>
    </t:RequestSecurityToken>
  </s:Body>
</s:Envelope>
EOF

$CURL $CURL_NOISE --connect-timeout 10 --max-time 120 -n $AUTH \
 -o $CURL_SAML_RESP \
 --data @$SAML_FILE \
 --ciphers AES256-SHA \
 -H 'accept:application/atom+xml;charset=utf-8' \
 https://login.microsoftonline.com/extSTS.srf

SAML_TOKEN=$(
    perl -lane 'print $1 if m!<wsse:BinarySecurityToken[^>]*>(.*)</wsse:BinarySecurityToken!' $CURL_SAML_RESP | \
	perl -p -e 's/&amp;/&/sg;s/&lt;/</sg;s/&gt;/>/sg;s/&quot;/"/sg;'
)

if test -n "$SAML_TOKEN"
then
    echo $SAML_TOKEN > $FORM_FILE
else
    echo GET SAML TOKEN FAILED
    exit 1
fi
    
$CURL $CURL_NOISE --connect-timeout 10 --max-time 120 -n $AUTH \
 -o /dev/null \
 -c $COOKIE_FILE \
 --data @$FORM_FILE \
 --ciphers AES256-SHA \
 -H "HOST:$SITE" \
 -L "https://$SITE/_forms/default.aspx?wa=wsignin1.0"

if test $(egrep '(rtFa|FedAuth)' $COOKIE_FILE | wc -l) != "2"
then
    echo GET COOKIES FAILED
    exit 1
fi

COOKIE1=$(perl -lane 'print "$1=$2" if m!(rtFa)\s+(\S+)!' $COOKIE_FILE)
COOKIE2=$(perl -lane 'print "$1=$2" if m!(FedAuth)\s+(\S+)!' $COOKIE_FILE)

$CURL $CURL_NOISE --connect-timeout 10 --max-time 120 -n $AUTH \
 --data "''" \
 --ciphers AES256-SHA \
 -H "Cookie:$COOKIE1;$COOKIE2" \
 -H 'accept:application/atom+xml;charset=utf-8' \
 -o $CURL_DGST_RESP \
 "$CLOUD_SP/_api/contextinfo"

DIGEST=$(perl -lane 'print "Authorization:Bearer $1" if m!<d:FormDigestValue[^>]*>(.*)</d:FormDigestValue!' $CURL_DGST_RESP)
DIGEST_TIMEOUT=$(perl -lane 'print $1 if m!<d:FormDigestTimeoutSeconds[^>]*>(.*)</d:FormDigestTimeoutSeconds!' $CURL_DGST_RESP)

if test -z "$DIGEST"
then
    echo GET DIGEST FAILED
    exit 1
fi

#
# Read list meta data
#
cp /dev/null $CURL_HDR
cp /dev/null $CURL_RESP

/usr/bin/curl -s --max-time 30 -n $AUTH \
 --dump-header $CURL_HDR     \
 --ciphers AES256-SHA \
 -H 'accept:application/atom+xml;charset=utf-8' \
 -H "Cookie:$COOKIE1;$COOKIE2" \
 -H "$DIGEST" \
 -o $CURL_RESP \
 "$CLOUD_SP/_api/lists/getByTitle('$SP_LIST')"

if test -s $CURL_RESP
then
	for s in Created EntityTypeName Id ItemCount LastItemDeletedDate LastItemModifiedDate LastItemUserModifiedDate ListItemEntityTypeFullName Title
	do
		perl -lane 'print "$1=$2" if m!<d:('$s')[^>]*>([^<]+)!' $CURL_RESP
	done | tee $DOT_FILE | sed -e 's/^/Read list meta data /'
fi

source $DOT_FILE

#
# Create item
#
cp /dev/null $CURL_HDR
cp /dev/null $CURL_RESP

/usr/bin/curl -s --max-time 30 -n $AUTH \
 --dump-header $CURL_HDR     \
 --ciphers AES256-SHA \
 -H 'accept:application/atom+xml;charset=utf-8' \
 -H "Cookie:$COOKIE1;$COOKIE2" \
 -H "$DIGEST" \
 -o $CURL_RESP \
 -X POST        \
 --data "{ '__metadata': { 'type': '$ListItemEntityTypeFullName' }, 'Title': 'New-18999' }" \
 -H 'content-type:application/json;odata=verbose' \
 -H 'IF-MATCH:*' \
 "$CLOUD_SP/_api/lists/getByTitle('$SP_LIST')/items"

if test -s $CURL_RESP
then
	for s in Created Id Modified Title
	do
		perl -lane 'print "$1=$2" if m!<d:('$s')[^>]*>([^<]+)!' $CURL_RESP
	done | tee $DOT_FILE | sed -e 's/^/Create item /'
fi

source $DOT_FILE

#
# Update item
#
cp /dev/null $CURL_HDR
cp /dev/null $CURL_RESP

/usr/bin/curl -s --max-time 30 -n $AUTH \
 --dump-header $CURL_HDR     \
 --ciphers AES256-SHA \
 -H 'accept:application/atom+xml;charset=utf-8' \
 -H "Cookie:$COOKIE1;$COOKIE2" \
 -H "$DIGEST" \
 -o $CURL_RESP \
 -X MERGE       \
 --data "{ '__metadata': { 'type': '$ListItemEntityTypeFullName' }, 'Title': 'Updated-18999' }" \
 -H 'content-type:application/json;odata=verbose' \
 -H 'IF-MATCH:*' \
 "$CLOUD_SP/_api/lists/getByTitle('$SP_LIST')/items($Id)"

egrep '^HTTP' $CURL_HDR | sed -e "s/^/Update item $id /"

#
# Read item
#
cp /dev/null $CURL_HDR
cp /dev/null $CURL_RESP

/usr/bin/curl -s --max-time 30 -n $AUTH \
 --dump-header $CURL_HDR     \
 --ciphers AES256-SHA \
 -H 'accept:application/atom+xml;charset=utf-8' \
 -H "Cookie:$COOKIE1;$COOKIE2" \
 -H "$DIGEST" \
 -o $CURL_RESP \
 "$CLOUD_SP/_api/lists/getByTitle('$SP_LIST')/items?%24filter=ID%20eq%20$Id"

if test -s $CURL_RESP
then
	for s in Created Id Modified Title
	do
		perl -lane 'print "$1=$2" if m!<d:('$s')[^>]*>([^<]+)!' $CURL_RESP
	done | tee $DOT_FILE | sed -e 's/^/Read item /'
fi

#
# Delete item
#
cp /dev/null $CURL_HDR
cp /dev/null $CURL_RESP

/usr/bin/curl -s --max-time 30 -n $AUTH \
 --dump-header $CURL_HDR     \
 --ciphers AES256-SHA \
 -H 'accept:application/atom+xml;charset=utf-8' \
 -H "Cookie:$COOKIE1;$COOKIE2" \
 -H "$DIGEST" \
 -o $CURL_RESP \
 -X DELETE      \
 -H 'IF-MATCH:*' \
 "$CLOUD_SP/_api/lists/getByTitle('$SP_LIST')/items($Id)"

egrep '^HTTP' $CURL_HDR | sed -e "s/^/Delete item $Id /"

#
# Read list items
#
cp /dev/null $CURL_HDR
cp /dev/null $CURL_RESP

/usr/bin/curl -s --max-time 30 -n $AUTH \
 --dump-header $CURL_HDR     \
 --ciphers AES256-SHA \
 -H 'accept:application/atom+xml;charset=utf-8' \
 -H "Cookie:$COOKIE1;$COOKIE2" \
 -H "$DIGEST" \
 -o $CURL_RESP \
 "$CLOUD_SP/_api/lists/getByTitle('$SP_LIST')/items?%24top=1"

if test -s $CURL_RESP
then
	for s in Created Id Modified Title
	do
		perl -lane 'print "$1=$2" if m!<d:('$s')[^>]*>([^<]+)!' $CURL_RESP
	done | tee $DOT_FILE | sed -e 's/^/Read list /'
fi
